version: '2'
services:
  app:
    container_name: ${DOCKER_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: dev
    depends_on:
      - redis
    links:
      - redis

  redis:
    container_name: ${DOCKER_PROJECT_NAME}_redis_cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - rediscache:/data
volumes:
  rediscache:
